//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acheter
    {
        public int Etudiant { get; set; }
        public int Ouvrage { get; set; }
        public Nullable<System.DateTime> date_Acheter { get; set; }
    }
}
