//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authentification
    {
        public string User_Name { get; set; }
        public string Password_cle { get; set; }
        public string Roles { get; set; }
        public string Name { get; set; }
        public string prenom { get; set; }
        public string Email { get; set; }
        public string Confirmpassword { get; set; }
        public string Photouser { get; set; }
    }
}
